frenet_optimal_planner:
  _target_: devkit.sim_engine.planning.planner.local_planner.predefined_maneuver_mode_sampling_planner.PredefinedManeuverModeSamplingPlanner
  _convert_: "all"

  planner_settings:
    _target_: devkit.sim_engine.planning.planner.local_planner.predefined_maneuver_mode_sampling_planner.PredefinedManeuverModeSamplingPlannerSettings
    _convert_: all

    num_width: 3 # road width方向的 sampling number
    num_jerk: 5 # jerk sampling number

    max_road_width: null # maximum road width [m]
    highest_speed: null # highest sampling speed [m/s] 赋值为 None
    highest_jerk: 9.0  # highest sampling jerk [m/s^3]
    lon_accel_max: 8.2  #  [m/s^2]
    lon_accel_min: -8.2  #  [m/s^2]

  planned_trajectory_samples: 16 # Number of trajectory samples to generate
  planned_trajectory_sample_interval: 0.5 # The sampling time interval between samples [s]
  truck_lateral_expansion_factor: 1.3 #- 注意： 因为矿车较宽，增加一个侧向宽度膨胀系数,[m] float; 大于1.0

  thread_safe: true # 构建 planner，确保只保留 1 个非线程安全的实例

