simulation_log_callback:
  _target_: devkit.sim_engine.callback.simulation_log_callback.SimulationLogCallback
  _convert_: 'all'

  output_directory: ${output_dir}
  simulation_log_dir: simulation_log      # Simulation log dir
  serialization_type: "pickle"           # A way to serialize output, options: ["pickle", "msgpack"]
